### ISSUE TITLE
Light Theme Sidebar Issues

### ISSUE THREAD

**Issue by NotGeri** [Bloom-host/BloomDocs#276]
### Page name

All

### Type

The information on that page is incorrect

### More information

It seems like the sidebar in light theme stays dark and the font is very hard to read: 

![img](https://i.geri.dev/cbc6fff4c56a95322ee1019ccd10a0.gif)

Tested on all major browsers

**Comment by p-rohitt** [comment]
Hey @NotGeri , I can work on this!

**Comment by NotGeri** [comment]
Thank you, it would be much appreciated!

**Comment by NotGeri** [comment]
I found some more minor issues like this, but I'll address them in #280
