### ISSUE TITLE
Sidebar Still Showing 1.19

### ISSUE THREAD

**Issue by NotGeri** [Bloom-host/BloomDocs#277]
### Page name

Sidebar

### Type

The information on that page is outdated

### More information

We should probably remove this at this point 😄 

![image](https://github.com/Bloom-host/BloomDocs/assets/46295973/64f9b85c-25f3-477b-9f9b-fd8f54f821f5)

**Comment by PraveenShinde3** [comment]
Hi @NotGeri I have updated the sidebar.js please verify the PR, thanks.
